---
abstract: 'Perl 6 Syntax Highlighter'
author:
  - 'Written by Ahmad M. Zawawi C<< <ahmad.zawawi at gmail.com> >> '
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Highlight-Perl6
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.63
  Readonly: 1.03
  Term::ANSIColor: 1.12
  YAML::Syck: 1.04
  perl: 5.01
version: 0.0296
