--- #YAML:1.0
name:                Syntax-Highlight-Perl6
version:             0.02
abstract:            Perl 6 syntax highlighter
license:             ~
author:              
    - Ahmad M. Zawawi <ahmad.zawawi@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Moose:                         Term::ANSIColor
    YAML::Syck:                    
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
