---
abstract: 'Perl 6 Syntax Highlighter'
author:
  - 'Written by Ahmad M. Zawawi C<< <ahmad.zawawi at gmail.com> >> '
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.27
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Highlight-Perl6
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.89
  Term::ANSIColor: 2.00
  YAML::XS: 0.32
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.81
