---
abstract: 'Perl 6 Syntax Highlighter'
author:
  - 'Ahmad M. Zawawi'
build_requires:
  Test::Exception: 0.27
  Test::More: 0.86
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Highlight-Perl6
provides:
  Syntax::Highlight::Perl6:
    file: lib/Syntax/Highlight/Perl6.pm
    version: 0.86
  Syntax::Highlight::Perl6::Actions:
    file: lib/Syntax/Highlight/Perl6.pm
requires:
  STD: 32116
  Term::ANSIColor: 2.00
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Syntax-Highlight-Perl6/
version: 0.86
